[package]
name = "nano_crl2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "2.1.1"

[lib]
name = "nano_crl2"
src = "src/lib.rs"
